server:
  port: 8003
spring:
#  #  임시 db
#  readdb:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://yjhome.kro.kr:3306/read?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: qwer1234!
#    hikari:
#      maximum-pool-size: 10
#  writedb:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://yjhome.kro.kr:3306/scheduler?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: qwer1234!
#    hikari:
#      maximum-pool-size: 10

  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://gutsandgun.kro.kr:12008/scheduler?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gutsandgun
    hikari:
      maximum-pool-size: 10
  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://gutsandgun.kro.kr:12002/read?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: root
    password: gutsandgun
    hikari:
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    open-in-view: false
#    show-sql: true
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
        format_sql: true
#        show_sql: true




logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # query의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여줌


feign:
  url:
    sending-manager : localhost:8004
    sending-scheduler : localhost:8003